# Generated by Django 4.2.30 on 2026-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='参数模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('schema', models.JSONField(verbose_name='参数校验规则JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '参数模板',
                'verbose_name_plural': '参数模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(choices=[(1, '优先级1'), (2, '优先级2'), (3, '优先级3'), (4, '优先级4'), (5, '优先级5')], default=3, verbose_name='优先级')),
                ('parameters', models.JSONField(verbose_name='任务参数')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='task_models/', verbose_name='模型文件')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='task_results/', verbose_name='结果文件')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('last_operation_at', models.DateTimeField(auto_now=True, verbose_name='最后操作时间')),
            ],
            options={
                'verbose_name': '仿真任务',
                'verbose_name_plural': '仿真任务',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
