# Generated by Django 4.2.30 on 2026-06-16 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='task',
            name='parameter_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.parameterschema', verbose_name='使用的参数模板'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='task',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='parameterschema',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemas', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
