# Generated by Django 4.2.30 on 2026-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_days', models.IntegerField(default=180, help_text='超过该天数的已完成/失败任务将自动归档', verbose_name='自动归档天数')),
                ('cleanup_days', models.IntegerField(default=90, help_text='超过该天数的归档任务将被永久删除', verbose_name='自动清理天数')),
                ('max_file_size_mb', models.IntegerField(default=100, help_text='上传模型文件的最大大小限制', verbose_name='最大文件大小(MB)')),
                ('max_concurrent_tasks', models.IntegerField(default=4, help_text='同时运行的仿真任务数量上限', verbose_name='最大并发任务数')),
                ('storage_quota_gb', models.IntegerField(default=100, help_text='系统总存储空间配额', verbose_name='存储配额(GB)')),
                ('task_timeout_hours', models.IntegerField(default=4, help_text='单个仿真任务的最大运行时间', verbose_name='任务超时时间(小时)')),
                ('enable_email_notification', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('enable_auto_cleanup', models.BooleanField(default=True, verbose_name='启用自动清理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
